CREATE TABLE IF NOT EXISTS activites (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO activites (nom) VALUES
('Boulangerie / Pâtisserie'),
('Charcuterie / Traiteur'),
('Boucherie'),
('Poissonnerie'),
('Fromagerie / Crèmerie'),
('Épicerie fine'),
('Primeur (fruits et légumes)'),
('Caviste (vins et spiritueux)'),
('Chocolaterie / Confiserie'),
('Glacier artisanal'),
('Restaurant'),
('Brasserie / Bistrot'),
('Pizzeria'),
('Sandwicherie / Snack'),
('Fast-food'),
('Food truck'),
('Crêperie'),
('Salon de thé'),
('Café / Bar'),
('Bar à vin'),
('Bar à jus / Smoothie bar'),
('Superette / Supérette de quartier'),
('Magasin bio'),
('Boutique vrac'),
('Boutique de vêtements'),
('Magasin de chaussures'),
('Boutique de lingerie'),
('Magasin de sport'),
('Boutique de maroquinerie (sacs, ceintures, etc.)'),
('Bijouterie / Joaillerie'),
('Horlogerie'),
('Opticien'),
('Boutique d’accessoires (chapeaux, foulards, lunettes, etc.)'),
('Coiffeur / Barbier'),
('Esthéticienne / Institut de beauté'),
('Tatoueur / Piercing'),
('Cordonnier'),
('Serrurier'),
('Tailleur / Retouche'),
('Ébéniste / Menuisier'),
('Céramiste / Potier'),
('Fleuriste'),
('Photographe'),
('Papeterie / Librairie'),
('Magasin de jouets'),
('Librairie ésotérique / bien-être'),
('Pharmacie / Parapharmacie'),
('Parfumerie / Boutique cosmétique'),
('Laverie automatique'),
('Pressing'),
('Agence de voyage'),
('Magasin informatique / téléphonie'),
('Centre de reprographie / impression');